### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by rinetzky** [elazarg/ubpf#33]
- [x] add programs like simple_lt abd simple_neq which the current verifier succeeds on.

- [x] add a simple_loop like program where we only use pointers (no integers. hopefully, go forward not backwards)

- [x] program like mapcpy which reads length from start of packet, reads the rest of data of length bytes compute checksum and compare to other field  

- [x] (low priority) in mapcpy check if modulo access w/o loop works 
value1[i % VALUE_SIZE + 1] = value2[i % VALUE_SIZE];

- [x] memset() resets from begining to end

**Comment by elazarg** [comment]
Added a "simple_eq" that the current veirfier does _not_ succeed on, for unknown reason. Should investigate.
